# -*- coding: utf-8 -*-
"""accesslayerswitchauto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X87eVyKpsE3q760KmLcmSzr2hvN1VB_F
"""

pip install netmiko

import paramiko
import time 

# importing paramiko and time lib

# hosts configured for python run
ip_address = 192.168.122.64 
username = "pythonauto"
password = "python123"
# invoking a paramiko sshclient method
ssh_Client = paramiko.SSHClient()
#key policies try to improve.
ssh_Client.set_missing_host_key_policy(paramiko.AutoAddpolicy())
#setting variables
ssh_Client.connect(hostname = ip_address,username=username,password = password)

print "ssh connection successfull shell on the device" , ip_address
# invoking shell on sshclient and 
connectto = ssh_Client.invokeshell()
# create python user with privilege level 15 to achive exec status
connectto.send("conf t"\n)
#creating vlans via a for loop
for n in range (2,7):
  connectto.send("vlan" +str(n) + "/n")
  connectto.send("name python_vlan" + str(n)+ "/n" ) 
  print("python_vlan" + str(n) + "is created")
  time.sleep(0.25)
connectto.send("show vlan bri")
connectto.send("show run")
time.sleep(4)
connectto.send("end"\n)
#exiting from cisco CLI
time.sleep(1)
console_output = connectto.recv(65535)
print console_output

#creating a file and saving the configs locally

file = open("pythonvlanscriptOutput.txt","w+")
output = connectto.readlines()
file.write(''.join(output))
file.close() 

#try to upload this to github via an ansible playbook or jenkins









ssh_client.close()